// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF38lH97c760JmpV4VVioAltuKNrNirJw',
    appId: '1:969380361735:web:bcf943232ebb17f6185ca2',
    messagingSenderId: '969380361735',
    projectId: 'fir-auth-with-bloc-38dee',
    authDomain: 'fir-auth-with-bloc-38dee.firebaseapp.com',
    storageBucket: 'fir-auth-with-bloc-38dee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQjW7zOprEKhoBoPbq9hCsWzbI5c3tyM',
    appId: '1:969380361735:android:2e893eeb0a63bcaa185ca2',
    messagingSenderId: '969380361735',
    projectId: 'fir-auth-with-bloc-38dee',
    storageBucket: 'fir-auth-with-bloc-38dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQri015-SWrbwdXNFYCO7K3gxR0CIVfIY',
    appId: '1:969380361735:ios:acd1468912095dec185ca2',
    messagingSenderId: '969380361735',
    projectId: 'fir-auth-with-bloc-38dee',
    storageBucket: 'fir-auth-with-bloc-38dee.appspot.com',
    iosBundleId: 'com.example.gAuthWithBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQri015-SWrbwdXNFYCO7K3gxR0CIVfIY',
    appId: '1:969380361735:ios:e4bf05d70eed379c185ca2',
    messagingSenderId: '969380361735',
    projectId: 'fir-auth-with-bloc-38dee',
    storageBucket: 'fir-auth-with-bloc-38dee.appspot.com',
    iosBundleId: 'com.example.gAuthWithBloc.RunnerTests',
  );
}
